FROM node:13.14.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY ./package.json ./
COPY ./package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY ./ ./
RUN npm run build

# use nginx alpine to serve static files
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html

# expose http and https ports
EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
