version: '3.7'

services:
  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # map volumes to hot reload work
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - 3001:3000

  server:
    stdin_open: true
    build:
      context: ../reactnd-contacts-server
      dockerfile: Dockerfile
    command: nodemon server.js
    volumes:
      # map volumes to hot reload work
      - ../reactnd-contacts-server:/app
      - ../reactnd-contacts-server/node_modules:/app/node_modules
    ports:
      - 5001:5001
