version: '3.7'

services:
  server:
    stdin_open: true
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    command: nodemon server.js
    volumes:
      # map volumes to hot reload work
      - ./:/app
      - ./node_modules:/app/node_modules
    ports:
      - 5001:5001
      - 5002:5002